const http=require("http"),https=require("https"),fs=require("fs");const{URL}=require("url");

function clean(v){return v?v.replace(/\s+/g," ").trim():null}

function attrs(tag){const r={};for(const m of tag.matchAll(/([:\w-]+)\s*=\s*["']([^"']*)["']/g))r[m[1].toLowerCase()]=m[2];return r}

function findEnd(html,start,tag){const re=new RegExp("<\\/?"+tag+"\\b[^>]*>","gi");re.lastIndex=start;let depth=0,m;while((m=re.exec(html))){if(/^<\//.test(m[0])){depth--;if(depth===0)return m.index+m[0].length}else depth++}return-1}

function findEvents(html,url){const events=[];const re=/<([a-z0-9]+)\b[^>]*>/gi;let m;while((m=re.exec(html))){const open=m[0],a=attrs(open);if(!/\bitemscope\b/i.test(open)&&!a.itemprop&&!a.typeof)continue;const type=(a.itemtype||a.typeof||"").toLowerCase();if(!/event|musicevent|festival|exhibitionevent/.test(type)&&!a.itemprop)continue;const end=findEnd(html,m.index,m[1]);if(end<0)continue;const block=html.slice(m.index,end),data={};for(const x of block.matchAll(/<([a-z0-9]+)([^>]*)>/gi)){const at=attrs(x[0]);if(!at.itemprop)continue;let value=at.content||at.datetime||at.href||at.src||"";if(!value){const close=block.indexOf("</"+x[1]+">",x.index);if(close>=0)value=block.slice(x.index+x[0].length,close).replace(/<[^>]+>/g," ")}value=clean(value);if(value)data[at.itemprop]=value}if(Object.keys(data).length)events.push({url,type:type||null,data})}return events}

function extract(url){return new Promise((resolve,reject)=>{const u=new URL(url),client=u.protocol==="https:"?https:http;const req=client.get(u,{headers:{"User-Agent":"Mozilla/5.0 AroundoCrawler/1.0"}},res=>{let html="";res.setEncoding("utf8");res.on("data",c=>html+=c);res.on("end",()=>resolve({acquisizione:{status:res.statusCode,contentType:res.headers["content-type"]||null,url},eventi:findEvents(html,url),content:html}))});req.setTimeout(20000,()=>req.destroy(new Error("Timeout")));req.on("error",reject)})}

http.createServer(async(req,res)=>{const q=new URL(req.url,"http://localhost:3002"),url=q.searchParams.get("url");if(q.pathname==="/"&&!url){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});return res.end(fs.readFileSync(__dirname+"/viewer.html"))}res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Content-Type","application/json; charset=utf-8");if(!url)return res.end(JSON.stringify({error:"URL mancante"}));try{res.end(JSON.stringify(await extract(url)))}catch(e){res.end(JSON.stringify({error:e.message}))}}).listen(3002,()=>console.log("Structured attivo sulla porta 3002"));